/*
 * SPDX-FileCopyrightText: 2025 Pexip AS
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package config

// ConferenceSyncTemplate represents a conference sync template configuration
type ConferenceSyncTemplate struct {
	ID                                         int    `json:"id,omitempty"`
	Name                                       string `json:"name"`
	Description                                string `json:"description,omitempty"`
	LdapSyncSource                             string `json:"ldap_sync_source,omitempty"`
	LdapUserFilter                             string `json:"ldap_user_filter"`
	LdapUserSearchDN                           string `json:"ldap_user_search_dn,omitempty"`
	EnableAutomaticSync                        bool   `json:"enable_automatic_sync"`
	SyncConferences                            bool   `json:"sync_conferences"`
	SyncDevices                                bool   `json:"sync_devices"`
	SyncEndUsers                               bool   `json:"sync_end_users"`
	EnableServiceEmails                        bool   `json:"enable_service_emails"`
	SMTPServer                                 string `json:"smtp_server,omitempty"`
	ServiceEmailSubjectTemplate                string `json:"service_email_subject_template,omitempty"`
	ServiceEmailTemplate                       string `json:"service_email_template,omitempty"`
	DeviceEmailSubjectTemplate                 string `json:"device_email_subject_template,omitempty"`
	DeviceEmailTemplate                        string `json:"device_email_template,omitempty"`
	ConferenceName                             string `json:"conference_name,omitempty"`
	ConferenceDescription                      string `json:"conference_description,omitempty"`
	ConferenceDescriptionOverridable           bool   `json:"conference_description_overridable"`
	ServiceType                                string `json:"service_type"`
	Tag                                        string `json:"tag,omitempty"`
	TagOverridable                             bool   `json:"tag_overridable"`
	PIN                                        string `json:"pin,omitempty"`
	GuestPIN                                   string `json:"guest_pin,omitempty"`
	PINSettingsOverridable                     bool   `json:"pin_settings_overridable"`
	AllowGuests                                bool   `json:"allow_guests"`
	CallType                                   string `json:"call_type"`
	CallTypeOverridable                        bool   `json:"call_type_overridable"`
	CryptoMode                                 string `json:"crypto_mode,omitempty"`
	CryptoModeOverridable                      bool   `json:"crypto_mode_overridable"`
	EnableChat                                 string `json:"enable_chat"`
	EnableChatOverridable                      bool   `json:"enable_chat_overridable"`
	EnableOverlayText                          bool   `json:"enable_overlay_text"`
	EnableActiveSpeakerIndication              bool   `json:"enable_active_speaker_indication"`
	HostView                                   string `json:"host_view"`
	HostViewOverridable                        bool   `json:"host_view_overridable"`
	GuestsCanPresent                           bool   `json:"guests_can_present"`
	GuestsCanPresentOverridable                bool   `json:"guests_can_present_overridable"`
	DirectMedia                                string `json:"direct_media"`
	DirectMediaOverridable                     bool   `json:"direct_media_overridable"`
	DirectMediaNotificationDuration            int    `json:"direct_media_notification_duration"`
	DirectMediaNotificationDurationOverridable bool   `json:"direct_media_notification_duration_overridable"`
	MaxCallrateIn                              *int   `json:"max_callrate_in,omitempty"`
	MaxCallrateOut                             *int   `json:"max_callrate_out,omitempty"`
	CallratesOverridable                       bool   `json:"callrates_overridable"`
	MaxPixelsPerSecond                         string `json:"max_pixels_per_second,omitempty"`
	MaxPixelsPerSecondOverridable              bool   `json:"max_pixels_per_second_overridable"`
	ParticipantLimit                           *int   `json:"participant_limit,omitempty"`
	ParticipantLimitOverridable                bool   `json:"participant_limit_overridable"`
	PrimaryOwnerEmailAddress                   string `json:"primary_owner_email_address,omitempty"`
	PrimaryOwnerEmailAddressOverridable        bool   `json:"primary_owner_email_address_overridable"`
	HostIdentityProviderGroup                  string `json:"host_identity_provider_group,omitempty"`
	GuestIdentityProviderGroup                 string `json:"guest_identity_provider_group,omitempty"`
	NonIdpParticipants                         string `json:"non_idp_participants"`
	IdpSettingsOverridable                     bool   `json:"idp_settings_overridable"`
	IVRTheme                                   string `json:"ivr_theme,omitempty"`
	IVRThemeOverridable                        bool   `json:"ivr_theme_overridable"`
	Alias1                                     string `json:"alias_1,omitempty"`
	Alias1Description                          string `json:"alias_1_description,omitempty"`
	Alias2                                     string `json:"alias_2,omitempty"`
	Alias2Description                          string `json:"alias_2_description,omitempty"`
	Alias3                                     string `json:"alias_3,omitempty"`
	Alias3Description                          string `json:"alias_3_description,omitempty"`
	Alias4                                     string `json:"alias_4,omitempty"`
	Alias4Description                          string `json:"alias_4_description,omitempty"`
	Alias5                                     string `json:"alias_5,omitempty"`
	Alias5Description                          string `json:"alias_5_description,omitempty"`
	Alias6                                     string `json:"alias_6,omitempty"`
	Alias6Description                          string `json:"alias_6_description,omitempty"`
	Alias7                                     string `json:"alias_7,omitempty"`
	Alias7Description                          string `json:"alias_7_description,omitempty"`
	Alias8                                     string `json:"alias_8,omitempty"`
	Alias8Description                          string `json:"alias_8_description,omitempty"`
	AliasesOverridable                         bool   `json:"aliases_overridable"`
	DeviceUsername                             string `json:"device_username,omitempty"`
	DeviceUsernameOverridable                  bool   `json:"device_username_overridable"`
	DevicePassword                             string `json:"device_password,omitempty"`
	DevicePasswordOverridable                  bool   `json:"device_password_overridable"`
	DeviceAlias                                string `json:"device_alias,omitempty"`
	DeviceDescription                          string `json:"device_description,omitempty"`
	DeviceDescriptionOverridable               bool   `json:"device_description_overridable"`
	DeviceTag                                  string `json:"device_tag,omitempty"`
	DeviceTagOverridable                       bool   `json:"device_tag_overridable"`
	DeviceEnableSIP                            bool   `json:"device_enable_sip"`
	DeviceEnableH323                           bool   `json:"device_enable_h323"`
	DeviceEnableInfinityConnectNonSSO          bool   `json:"device_enable_infinity_connect_non_sso"`
	DeviceEnableInfinityConnectSSO             bool   `json:"device_enable_infinity_connect_sso"`
	DeviceEnableStandardSSO                    bool   `json:"device_enable_standard_sso"`
	DeviceRegistrationTypesOverridable         bool   `json:"device_registration_types_overridable"`
	DeviceSSOIdentityProviderGroup             string `json:"device_sso_identity_provider_group,omitempty"`
	DeviceSyncIfAccountDisabled                bool   `json:"device_sync_if_account_disabled"`
	EndUserUUID                                string `json:"end_user_uuid,omitempty"`
	EndUserFirstName                           string `json:"end_user_first_name,omitempty"`
	EndUserLastName                            string `json:"end_user_last_name,omitempty"`
	EndUserDisplayName                         string `json:"end_user_display_name,omitempty"`
	EndUserNamesOverridable                    bool   `json:"end_user_names_overridable"`
	EndUserDescription                         string `json:"end_user_description,omitempty"`
	EndUserDescriptionOverridable              bool   `json:"end_user_description_overridable"`
	EndUserTelephoneNumber                     string `json:"end_user_telephone_number,omitempty"`
	EndUserMobileNumber                        string `json:"end_user_mobile_number,omitempty"`
	EndUserContactsOverridable                 bool   `json:"end_user_contacts_overridable"`
	EndUserTitle                               string `json:"end_user_title,omitempty"`
	EndUserDepartment                          string `json:"end_user_department,omitempty"`
	EndUserMSExchangeGUID                      string `json:"end_user_ms_exchange_guid,omitempty"`
	EndUserAvatarURL                           string `json:"end_user_avatar_url,omitempty"`
	EndUserOtherPersonalOverridable            bool   `json:"end_user_other_personal_overridable"`
	EndUserAdvancedOverridable                 bool   `json:"end_user_advanced_overridable"`
	ResourceURI                                string `json:"resource_uri,omitempty"`
}

// ConferenceSyncTemplateCreateRequest represents a request to create a conference sync template
type ConferenceSyncTemplateCreateRequest struct {
	Name                                       string `json:"name"`
	Description                                string `json:"description,omitempty"`
	LdapSyncSource                             string `json:"ldap_sync_source,omitempty"`
	LdapUserFilter                             string `json:"ldap_user_filter"`
	LdapUserSearchDN                           string `json:"ldap_user_search_dn,omitempty"`
	EnableAutomaticSync                        bool   `json:"enable_automatic_sync"`
	SyncConferences                            bool   `json:"sync_conferences"`
	SyncDevices                                bool   `json:"sync_devices"`
	SyncEndUsers                               bool   `json:"sync_end_users"`
	EnableServiceEmails                        bool   `json:"enable_service_emails"`
	SMTPServer                                 string `json:"smtp_server,omitempty"`
	ServiceEmailSubjectTemplate                string `json:"service_email_subject_template,omitempty"`
	ServiceEmailTemplate                       string `json:"service_email_template,omitempty"`
	DeviceEmailSubjectTemplate                 string `json:"device_email_subject_template,omitempty"`
	DeviceEmailTemplate                        string `json:"device_email_template,omitempty"`
	ConferenceName                             string `json:"conference_name,omitempty"`
	ConferenceDescription                      string `json:"conference_description,omitempty"`
	ConferenceDescriptionOverridable           bool   `json:"conference_description_overridable"`
	ServiceType                                string `json:"service_type"`
	Tag                                        string `json:"tag,omitempty"`
	TagOverridable                             bool   `json:"tag_overridable"`
	PIN                                        string `json:"pin,omitempty"`
	GuestPIN                                   string `json:"guest_pin,omitempty"`
	PINSettingsOverridable                     bool   `json:"pin_settings_overridable"`
	AllowGuests                                bool   `json:"allow_guests"`
	CallType                                   string `json:"call_type"`
	CallTypeOverridable                        bool   `json:"call_type_overridable"`
	CryptoMode                                 string `json:"crypto_mode,omitempty"`
	CryptoModeOverridable                      bool   `json:"crypto_mode_overridable"`
	EnableChat                                 string `json:"enable_chat"`
	EnableChatOverridable                      bool   `json:"enable_chat_overridable"`
	EnableOverlayText                          bool   `json:"enable_overlay_text"`
	EnableActiveSpeakerIndication              bool   `json:"enable_active_speaker_indication"`
	HostView                                   string `json:"host_view"`
	HostViewOverridable                        bool   `json:"host_view_overridable"`
	GuestsCanPresent                           bool   `json:"guests_can_present"`
	GuestsCanPresentOverridable                bool   `json:"guests_can_present_overridable"`
	DirectMedia                                string `json:"direct_media"`
	DirectMediaOverridable                     bool   `json:"direct_media_overridable"`
	DirectMediaNotificationDuration            int    `json:"direct_media_notification_duration"`
	DirectMediaNotificationDurationOverridable bool   `json:"direct_media_notification_duration_overridable"`
	MaxCallrateIn                              *int   `json:"max_callrate_in,omitempty"`
	MaxCallrateOut                             *int   `json:"max_callrate_out,omitempty"`
	CallratesOverridable                       bool   `json:"callrates_overridable"`
	MaxPixelsPerSecond                         string `json:"max_pixels_per_second,omitempty"`
	MaxPixelsPerSecondOverridable              bool   `json:"max_pixels_per_second_overridable"`
	ParticipantLimit                           *int   `json:"participant_limit,omitempty"`
	ParticipantLimitOverridable                bool   `json:"participant_limit_overridable"`
	PrimaryOwnerEmailAddress                   string `json:"primary_owner_email_address,omitempty"`
	PrimaryOwnerEmailAddressOverridable        bool   `json:"primary_owner_email_address_overridable"`
	HostIdentityProviderGroup                  string `json:"host_identity_provider_group,omitempty"`
	GuestIdentityProviderGroup                 string `json:"guest_identity_provider_group,omitempty"`
	NonIdpParticipants                         string `json:"non_idp_participants"`
	IdpSettingsOverridable                     bool   `json:"idp_settings_overridable"`
	IVRTheme                                   string `json:"ivr_theme,omitempty"`
	IVRThemeOverridable                        bool   `json:"ivr_theme_overridable"`
	Alias1                                     string `json:"alias_1,omitempty"`
	Alias1Description                          string `json:"alias_1_description,omitempty"`
	Alias2                                     string `json:"alias_2,omitempty"`
	Alias2Description                          string `json:"alias_2_description,omitempty"`
	Alias3                                     string `json:"alias_3,omitempty"`
	Alias3Description                          string `json:"alias_3_description,omitempty"`
	Alias4                                     string `json:"alias_4,omitempty"`
	Alias4Description                          string `json:"alias_4_description,omitempty"`
	Alias5                                     string `json:"alias_5,omitempty"`
	Alias5Description                          string `json:"alias_5_description,omitempty"`
	Alias6                                     string `json:"alias_6,omitempty"`
	Alias6Description                          string `json:"alias_6_description,omitempty"`
	Alias7                                     string `json:"alias_7,omitempty"`
	Alias7Description                          string `json:"alias_7_description,omitempty"`
	Alias8                                     string `json:"alias_8,omitempty"`
	Alias8Description                          string `json:"alias_8_description,omitempty"`
	AliasesOverridable                         bool   `json:"aliases_overridable"`
	DeviceUsername                             string `json:"device_username,omitempty"`
	DeviceUsernameOverridable                  bool   `json:"device_username_overridable"`
	DevicePassword                             string `json:"device_password,omitempty"`
	DevicePasswordOverridable                  bool   `json:"device_password_overridable"`
	DeviceAlias                                string `json:"device_alias,omitempty"`
	DeviceDescription                          string `json:"device_description,omitempty"`
	DeviceDescriptionOverridable               bool   `json:"device_description_overridable"`
	DeviceTag                                  string `json:"device_tag,omitempty"`
	DeviceTagOverridable                       bool   `json:"device_tag_overridable"`
	DeviceEnableSIP                            bool   `json:"device_enable_sip"`
	DeviceEnableH323                           bool   `json:"device_enable_h323"`
	DeviceEnableInfinityConnectNonSSO          bool   `json:"device_enable_infinity_connect_non_sso"`
	DeviceEnableInfinityConnectSSO             bool   `json:"device_enable_infinity_connect_sso"`
	DeviceEnableStandardSSO                    bool   `json:"device_enable_standard_sso"`
	DeviceRegistrationTypesOverridable         bool   `json:"device_registration_types_overridable"`
	DeviceSSOIdentityProviderGroup             string `json:"device_sso_identity_provider_group,omitempty"`
	DeviceSyncIfAccountDisabled                bool   `json:"device_sync_if_account_disabled"`
	EndUserUUID                                string `json:"end_user_uuid,omitempty"`
	EndUserFirstName                           string `json:"end_user_first_name,omitempty"`
	EndUserLastName                            string `json:"end_user_last_name,omitempty"`
	EndUserDisplayName                         string `json:"end_user_display_name,omitempty"`
	EndUserNamesOverridable                    bool   `json:"end_user_names_overridable"`
	EndUserDescription                         string `json:"end_user_description,omitempty"`
	EndUserDescriptionOverridable              bool   `json:"end_user_description_overridable"`
	EndUserTelephoneNumber                     string `json:"end_user_telephone_number,omitempty"`
	EndUserMobileNumber                        string `json:"end_user_mobile_number,omitempty"`
	EndUserContactsOverridable                 bool   `json:"end_user_contacts_overridable"`
	EndUserTitle                               string `json:"end_user_title,omitempty"`
	EndUserDepartment                          string `json:"end_user_department,omitempty"`
	EndUserMSExchangeGUID                      string `json:"end_user_ms_exchange_guid,omitempty"`
	EndUserAvatarURL                           string `json:"end_user_avatar_url,omitempty"`
	EndUserOtherPersonalOverridable            bool   `json:"end_user_other_personal_overridable"`
	EndUserAdvancedOverridable                 bool   `json:"end_user_advanced_overridable"`
}

// ConferenceSyncTemplateUpdateRequest represents a request to update a conference sync template
type ConferenceSyncTemplateUpdateRequest struct {
	Name                                       string `json:"name,omitempty"`
	Description                                string `json:"description,omitempty"`
	LdapSyncSource                             string `json:"ldap_sync_source,omitempty"`
	LdapUserFilter                             string `json:"ldap_user_filter,omitempty"`
	LdapUserSearchDN                           string `json:"ldap_user_search_dn,omitempty"`
	EnableAutomaticSync                        *bool  `json:"enable_automatic_sync,omitempty"`
	SyncConferences                            *bool  `json:"sync_conferences,omitempty"`
	SyncDevices                                *bool  `json:"sync_devices,omitempty"`
	SyncEndUsers                               *bool  `json:"sync_end_users,omitempty"`
	EnableServiceEmails                        *bool  `json:"enable_service_emails,omitempty"`
	SMTPServer                                 string `json:"smtp_server,omitempty"`
	ServiceEmailSubjectTemplate                string `json:"service_email_subject_template,omitempty"`
	ServiceEmailTemplate                       string `json:"service_email_template,omitempty"`
	DeviceEmailSubjectTemplate                 string `json:"device_email_subject_template,omitempty"`
	DeviceEmailTemplate                        string `json:"device_email_template,omitempty"`
	ConferenceName                             string `json:"conference_name,omitempty"`
	ConferenceDescription                      string `json:"conference_description,omitempty"`
	ConferenceDescriptionOverridable           *bool  `json:"conference_description_overridable,omitempty"`
	ServiceType                                string `json:"service_type,omitempty"`
	Tag                                        string `json:"tag,omitempty"`
	TagOverridable                             *bool  `json:"tag_overridable,omitempty"`
	PIN                                        string `json:"pin,omitempty"`
	GuestPIN                                   string `json:"guest_pin,omitempty"`
	PINSettingsOverridable                     *bool  `json:"pin_settings_overridable,omitempty"`
	AllowGuests                                *bool  `json:"allow_guests,omitempty"`
	CallType                                   string `json:"call_type,omitempty"`
	CallTypeOverridable                        *bool  `json:"call_type_overridable,omitempty"`
	CryptoMode                                 string `json:"crypto_mode,omitempty"`
	CryptoModeOverridable                      *bool  `json:"crypto_mode_overridable,omitempty"`
	EnableChat                                 string `json:"enable_chat,omitempty"`
	EnableChatOverridable                      *bool  `json:"enable_chat_overridable,omitempty"`
	EnableOverlayText                          *bool  `json:"enable_overlay_text,omitempty"`
	EnableActiveSpeakerIndication              *bool  `json:"enable_active_speaker_indication,omitempty"`
	HostView                                   string `json:"host_view,omitempty"`
	HostViewOverridable                        *bool  `json:"host_view_overridable,omitempty"`
	GuestsCanPresent                           *bool  `json:"guests_can_present,omitempty"`
	GuestsCanPresentOverridable                *bool  `json:"guests_can_present_overridable,omitempty"`
	DirectMedia                                string `json:"direct_media,omitempty"`
	DirectMediaOverridable                     *bool  `json:"direct_media_overridable,omitempty"`
	DirectMediaNotificationDuration            *int   `json:"direct_media_notification_duration,omitempty"`
	DirectMediaNotificationDurationOverridable *bool  `json:"direct_media_notification_duration_overridable,omitempty"`
	MaxCallrateIn                              *int   `json:"max_callrate_in,omitempty"`
	MaxCallrateOut                             *int   `json:"max_callrate_out,omitempty"`
	CallratesOverridable                       *bool  `json:"callrates_overridable,omitempty"`
	MaxPixelsPerSecond                         string `json:"max_pixels_per_second,omitempty"`
	MaxPixelsPerSecondOverridable              *bool  `json:"max_pixels_per_second_overridable,omitempty"`
	ParticipantLimit                           *int   `json:"participant_limit,omitempty"`
	ParticipantLimitOverridable                *bool  `json:"participant_limit_overridable,omitempty"`
	PrimaryOwnerEmailAddress                   string `json:"primary_owner_email_address,omitempty"`
	PrimaryOwnerEmailAddressOverridable        *bool  `json:"primary_owner_email_address_overridable,omitempty"`
	HostIdentityProviderGroup                  string `json:"host_identity_provider_group,omitempty"`
	GuestIdentityProviderGroup                 string `json:"guest_identity_provider_group,omitempty"`
	NonIdpParticipants                         string `json:"non_idp_participants,omitempty"`
	IdpSettingsOverridable                     *bool  `json:"idp_settings_overridable,omitempty"`
	IVRTheme                                   string `json:"ivr_theme,omitempty"`
	IVRThemeOverridable                        *bool  `json:"ivr_theme_overridable,omitempty"`
	Alias1                                     string `json:"alias_1,omitempty"`
	Alias1Description                          string `json:"alias_1_description,omitempty"`
	Alias2                                     string `json:"alias_2,omitempty"`
	Alias2Description                          string `json:"alias_2_description,omitempty"`
	Alias3                                     string `json:"alias_3,omitempty"`
	Alias3Description                          string `json:"alias_3_description,omitempty"`
	Alias4                                     string `json:"alias_4,omitempty"`
	Alias4Description                          string `json:"alias_4_description,omitempty"`
	Alias5                                     string `json:"alias_5,omitempty"`
	Alias5Description                          string `json:"alias_5_description,omitempty"`
	Alias6                                     string `json:"alias_6,omitempty"`
	Alias6Description                          string `json:"alias_6_description,omitempty"`
	Alias7                                     string `json:"alias_7,omitempty"`
	Alias7Description                          string `json:"alias_7_description,omitempty"`
	Alias8                                     string `json:"alias_8,omitempty"`
	Alias8Description                          string `json:"alias_8_description,omitempty"`
	AliasesOverridable                         *bool  `json:"aliases_overridable,omitempty"`
	DeviceUsername                             string `json:"device_username,omitempty"`
	DeviceUsernameOverridable                  *bool  `json:"device_username_overridable,omitempty"`
	DevicePassword                             string `json:"device_password,omitempty"`
	DevicePasswordOverridable                  *bool  `json:"device_password_overridable,omitempty"`
	DeviceAlias                                string `json:"device_alias,omitempty"`
	DeviceDescription                          string `json:"device_description,omitempty"`
	DeviceDescriptionOverridable               *bool  `json:"device_description_overridable,omitempty"`
	DeviceTag                                  string `json:"device_tag,omitempty"`
	DeviceTagOverridable                       *bool  `json:"device_tag_overridable,omitempty"`
	DeviceEnableSIP                            *bool  `json:"device_enable_sip,omitempty"`
	DeviceEnableH323                           *bool  `json:"device_enable_h323,omitempty"`
	DeviceEnableInfinityConnectNonSSO          *bool  `json:"device_enable_infinity_connect_non_sso,omitempty"`
	DeviceEnableInfinityConnectSSO             *bool  `json:"device_enable_infinity_connect_sso,omitempty"`
	DeviceEnableStandardSSO                    *bool  `json:"device_enable_standard_sso,omitempty"`
	DeviceRegistrationTypesOverridable         *bool  `json:"device_registration_types_overridable,omitempty"`
	DeviceSSOIdentityProviderGroup             string `json:"device_sso_identity_provider_group,omitempty"`
	DeviceSyncIfAccountDisabled                *bool  `json:"device_sync_if_account_disabled,omitempty"`
	EndUserUUID                                string `json:"end_user_uuid,omitempty"`
	EndUserFirstName                           string `json:"end_user_first_name,omitempty"`
	EndUserLastName                            string `json:"end_user_last_name,omitempty"`
	EndUserDisplayName                         string `json:"end_user_display_name,omitempty"`
	EndUserNamesOverridable                    *bool  `json:"end_user_names_overridable,omitempty"`
	EndUserDescription                         string `json:"end_user_description,omitempty"`
	EndUserDescriptionOverridable              *bool  `json:"end_user_description_overridable,omitempty"`
	EndUserTelephoneNumber                     string `json:"end_user_telephone_number,omitempty"`
	EndUserMobileNumber                        string `json:"end_user_mobile_number,omitempty"`
	EndUserContactsOverridable                 *bool  `json:"end_user_contacts_overridable,omitempty"`
	EndUserTitle                               string `json:"end_user_title,omitempty"`
	EndUserDepartment                          string `json:"end_user_department,omitempty"`
	EndUserMSExchangeGUID                      string `json:"end_user_ms_exchange_guid,omitempty"`
	EndUserAvatarURL                           string `json:"end_user_avatar_url,omitempty"`
	EndUserOtherPersonalOverridable            *bool  `json:"end_user_other_personal_overridable,omitempty"`
	EndUserAdvancedOverridable                 *bool  `json:"end_user_advanced_overridable,omitempty"`
}

// ConferenceSyncTemplateListResponse represents the response from listing conference sync templates
type ConferenceSyncTemplateListResponse struct {
	Meta struct {
		Limit      int    `json:"limit"`
		Next       string `json:"next"`
		Offset     int    `json:"offset"`
		Previous   string `json:"previous"`
		TotalCount int    `json:"total_count"`
	} `json:"meta"`
	Objects []ConferenceSyncTemplate `json:"objects"`
}
