/*
 * SPDX-FileCopyrightText: 2025 Pexip AS
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package config

// MsExchangeConnector represents a Microsoft Exchange connector configuration
type MsExchangeConnector struct {
	ID                         int     `json:"id,omitempty"`
	Name                       string  `json:"name"`
	Description                string  `json:"description,omitempty"`
	RoomMailboxEmailAddress    *string `json:"room_mailbox_email_address,omitempty"`
	RoomMailboxName            string  `json:"room_mailbox_name,omitempty"`
	URL                        string  `json:"url,omitempty"`
	Username                   string  `json:"username,omitempty"`
	Password                   string  `json:"password,omitempty"`
	AuthenticationMethod       string  `json:"authentication_method"`
	AuthProvider               string  `json:"auth_provider"`
	UUID                       string  `json:"uuid"`
	ScheduledAliasPrefix       *string `json:"scheduled_alias_prefix,omitempty"`
	ScheduledAliasDomain       string  `json:"scheduled_alias_domain,omitempty"`
	ScheduledAliasSuffixLength int     `json:"scheduled_alias_suffix_length"`
	MeetingBufferBefore        int     `json:"meeting_buffer_before"`
	MeetingBufferAfter         int     `json:"meeting_buffer_after"`
	EnableDynamicVmrs          bool    `json:"enable_dynamic_vmrs"`
	EnablePersonalVmrs         bool    `json:"enable_personal_vmrs"`
	AllowNewUsers              bool    `json:"allow_new_users"`
	DisableProxy               bool    `json:"disable_proxy"`
	UseCustomAddInSources      bool    `json:"use_custom_add_in_sources"`
	EnableAddinDebugLogs       bool    `json:"enable_addin_debug_logs"`
	// OAuth fields
	OauthClientID      *string `json:"oauth_client_id,omitempty"`
	OauthClientSecret  string  `json:"oauth_client_secret,omitempty"`
	OauthAuthEndpoint  string  `json:"oauth_auth_endpoint,omitempty"`
	OauthTokenEndpoint string  `json:"oauth_token_endpoint,omitempty"`
	OauthRedirectURI   string  `json:"oauth_redirect_uri,omitempty"`
	OauthRefreshToken  string  `json:"oauth_refresh_token,omitempty"`
	OauthState         *string `json:"oauth_state,omitempty"`
	// Kerberos fields
	KerberosRealm                  string `json:"kerberos_realm,omitempty"`
	KerberosKdc                    string `json:"kerberos_kdc,omitempty"`
	KerberosKdcHttpsProxy          string `json:"kerberos_kdc_https_proxy,omitempty"`
	KerberosExchangeSpn            string `json:"kerberos_exchange_spn,omitempty"`
	KerberosEnableTls              bool   `json:"kerberos_enable_tls"`
	KerberosAuthEveryRequest       bool   `json:"kerberos_auth_every_request"`
	KerberosVerifyTlsUsingCustomCa bool   `json:"kerberos_verify_tls_using_custom_ca"`
	// Add-in fields
	AddinServerDomain           string  `json:"addin_server_domain"`
	AddinDisplayName            string  `json:"addin_display_name"`
	AddinDescription            string  `json:"addin_description"`
	AddinProviderName           string  `json:"addin_provider_name"`
	AddinButtonLabel            string  `json:"addin_button_label"`
	AddinGroupLabel             string  `json:"addin_group_label"`
	AddinSupertipTitle          string  `json:"addin_supertip_title"`
	AddinSupertipDescription    string  `json:"addin_supertip_description"`
	AddinApplicationID          *string `json:"addin_application_id,omitempty"`
	AddinAuthorityURL           string  `json:"addin_authority_url,omitempty"`
	AddinOidcMetadataURL        string  `json:"addin_oidc_metadata_url,omitempty"`
	AddinAuthenticationMethod   string  `json:"addin_authentication_method"`
	AddinNaaWebApiApplicationID *string `json:"addin_naa_web_api_application_id,omitempty"`
	// Add-in pane fields
	AddinPaneTitle                                   string `json:"addin_pane_title"`
	AddinPaneDescription                             string `json:"addin_pane_description"`
	AddinPaneButtonTitle                             string `json:"addin_pane_button_title"`
	AddinPaneSuccessHeading                          string `json:"addin_pane_success_heading"`
	AddinPaneSuccessMessage                          string `json:"addin_pane_success_message"`
	AddinPaneAlreadyVideoMeetingHeading              string `json:"addin_pane_already_video_meeting_heading"`
	AddinPaneAlreadyVideoMeetingMessage              string `json:"addin_pane_already_video_meeting_message"`
	AddinPaneGeneralErrorHeading                     string `json:"addin_pane_general_error_heading"`
	AddinPaneGeneralErrorMessage                     string `json:"addin_pane_general_error_message"`
	AddinPaneManagementNodeDownHeading               string `json:"addin_pane_management_node_down_heading"`
	AddinPaneManagementNodeDownMessage               string `json:"addin_pane_management_node_down_message"`
	AddinPanePersonalVmrAddButton                    string `json:"addin_pane_personal_vmr_add_button"`
	AddinPanePersonalVmrSignInButton                 string `json:"addin_pane_personal_vmr_sign_in_button"`
	AddinPanePersonalVmrSelectMessage                string `json:"addin_pane_personal_vmr_select_message"`
	AddinPanePersonalVmrNoneMessage                  string `json:"addin_pane_personal_vmr_none_message"`
	AddinPanePersonalVmrErrorGettingMessage          string `json:"addin_pane_personal_vmr_error_getting_message"`
	AddinPanePersonalVmrErrorSigningInMessage        string `json:"addin_pane_personal_vmr_error_signing_in_message"`
	AddinPanePersonalVmrErrorInsertingMeetingMessage string `json:"addin_pane_personal_vmr_error_inserting_meeting_message"`
	// Personal VMR OAuth fields
	PersonalVmrOauthClientID                   *string `json:"personal_vmr_oauth_client_id,omitempty"`
	PersonalVmrOauthClientSecret               string  `json:"personal_vmr_oauth_client_secret,omitempty"`
	PersonalVmrOauthAuthEndpoint               string  `json:"personal_vmr_oauth_auth_endpoint,omitempty"`
	PersonalVmrOauthTokenEndpoint              string  `json:"personal_vmr_oauth_token_endpoint,omitempty"`
	PersonalVmrAdfsRelyingPartyTrustIdentifier string  `json:"personal_vmr_adfs_relying_party_trust_identifier,omitempty"`
	// Template fields
	MeetingInstructionsTemplate         string `json:"meeting_instructions_template,omitempty"`
	PersonalVmrInstructionsTemplate     string `json:"personal_vmr_instructions_template,omitempty"`
	PersonalVmrLocationTemplate         string `json:"personal_vmr_location_template,omitempty"`
	PersonalVmrNameTemplate             string `json:"personal_vmr_name_template,omitempty"`
	PersonalVmrDescriptionTemplate      string `json:"personal_vmr_description_template,omitempty"`
	PlaceholderInstructionsTemplate     string `json:"placeholder_instructions_template,omitempty"`
	ConferenceNameTemplate              string `json:"conference_name_template,omitempty"`
	ConferenceDescriptionTemplate       string `json:"conference_description_template,omitempty"`
	ConferenceSubjectTemplate           string `json:"conference_subject_template,omitempty"`
	ScheduledAliasDescriptionTemplate   string `json:"scheduled_alias_description_template,omitempty"`
	AcceptNewSingleMeetingTemplate      string `json:"accept_new_single_meeting_template,omitempty"`
	AcceptNewRecurringSeriesTemplate    string `json:"accept_new_recurring_series_template,omitempty"`
	AcceptEditedSingleMeetingTemplate   string `json:"accept_edited_single_meeting_template,omitempty"`
	AcceptEditedRecurringSeriesTemplate string `json:"accept_edited_recurring_series_template,omitempty"`
	AcceptEditedOccurrenceTemplate      string `json:"accept_edited_occurrence_template,omitempty"`
	RejectGeneralErrorTemplate          string `json:"reject_general_error_template,omitempty"`
	RejectAliasConflictTemplate         string `json:"reject_alias_conflict_template,omitempty"`
	RejectAliasDeletedTemplate          string `json:"reject_alias_deleted_template,omitempty"`
	RejectInvalidAliasIDTemplate        string `json:"reject_invalid_alias_id_template,omitempty"`
	RejectSingleMeetingPast             string `json:"reject_single_meeting_past,omitempty"`
	RejectRecurringSeriesPastTemplate   string `json:"reject_recurring_series_past_template,omitempty"`
	// JavaScript and CSS URLs
	OfficeJsURL                  string `json:"office_js_url"`
	MicrosoftFabricURL           string `json:"microsoft_fabric_url"`
	MicrosoftFabricComponentsURL string `json:"microsoft_fabric_components_url"`
	AdditionalAddInScriptSources string `json:"additional_add_in_script_sources,omitempty"`
	// Related resources
	Domains                   *string `json:"domains,omitempty"`
	HostIdentityProviderGroup *string `json:"host_identity_provider_group,omitempty"`
	IvrTheme                  *string `json:"ivr_theme,omitempty"`
	NonIdpParticipants        string  `json:"non_idp_participants,omitempty"`
	// Read-only fields
	PrivateKey  *string `json:"private_key,omitempty"`
	PublicKey   string  `json:"public_key,omitempty"`
	ResourceURI string  `json:"resource_uri,omitempty"`
}

// MsExchangeConnectorCreateRequest represents a request to create a Microsoft Exchange connector
type MsExchangeConnectorCreateRequest struct {
	Name                       string  `json:"name"`
	Description                string  `json:"description,omitempty"`
	RoomMailboxEmailAddress    *string `json:"room_mailbox_email_address,omitempty"`
	RoomMailboxName            string  `json:"room_mailbox_name,omitempty"`
	URL                        string  `json:"url,omitempty"`
	Username                   string  `json:"username,omitempty"`
	Password                   string  `json:"password,omitempty"`
	AuthenticationMethod       string  `json:"authentication_method"`
	AuthProvider               string  `json:"auth_provider"`
	UUID                       string  `json:"uuid"`
	ScheduledAliasPrefix       *string `json:"scheduled_alias_prefix,omitempty"`
	ScheduledAliasDomain       string  `json:"scheduled_alias_domain,omitempty"`
	ScheduledAliasSuffixLength int     `json:"scheduled_alias_suffix_length"`
	MeetingBufferBefore        int     `json:"meeting_buffer_before"`
	MeetingBufferAfter         int     `json:"meeting_buffer_after"`
	EnableDynamicVmrs          bool    `json:"enable_dynamic_vmrs"`
	EnablePersonalVmrs         bool    `json:"enable_personal_vmrs"`
	AllowNewUsers              bool    `json:"allow_new_users"`
	DisableProxy               bool    `json:"disable_proxy"`
	UseCustomAddInSources      bool    `json:"use_custom_add_in_sources"`
	EnableAddinDebugLogs       bool    `json:"enable_addin_debug_logs"`
	// OAuth fields
	OauthClientID      *string `json:"oauth_client_id,omitempty"`
	OauthClientSecret  string  `json:"oauth_client_secret,omitempty"`
	OauthAuthEndpoint  string  `json:"oauth_auth_endpoint,omitempty"`
	OauthTokenEndpoint string  `json:"oauth_token_endpoint,omitempty"`
	OauthRedirectURI   string  `json:"oauth_redirect_uri,omitempty"`
	OauthRefreshToken  string  `json:"oauth_refresh_token,omitempty"`
	// Kerberos fields
	KerberosRealm                  string `json:"kerberos_realm,omitempty"`
	KerberosKdc                    string `json:"kerberos_kdc,omitempty"`
	KerberosKdcHttpsProxy          string `json:"kerberos_kdc_https_proxy,omitempty"`
	KerberosExchangeSpn            string `json:"kerberos_exchange_spn,omitempty"`
	KerberosEnableTls              bool   `json:"kerberos_enable_tls"`
	KerberosAuthEveryRequest       bool   `json:"kerberos_auth_every_request"`
	KerberosVerifyTlsUsingCustomCa bool   `json:"kerberos_verify_tls_using_custom_ca"`
	// Add-in fields
	AddinServerDomain           string  `json:"addin_server_domain"`
	AddinDisplayName            string  `json:"addin_display_name"`
	AddinDescription            string  `json:"addin_description"`
	AddinProviderName           string  `json:"addin_provider_name"`
	AddinButtonLabel            string  `json:"addin_button_label"`
	AddinGroupLabel             string  `json:"addin_group_label"`
	AddinSupertipTitle          string  `json:"addin_supertip_title"`
	AddinSupertipDescription    string  `json:"addin_supertip_description"`
	AddinApplicationID          *string `json:"addin_application_id,omitempty"`
	AddinAuthorityURL           string  `json:"addin_authority_url,omitempty"`
	AddinOidcMetadataURL        string  `json:"addin_oidc_metadata_url,omitempty"`
	AddinAuthenticationMethod   string  `json:"addin_authentication_method"`
	AddinNaaWebApiApplicationID *string `json:"addin_naa_web_api_application_id,omitempty"`
	// Add-in pane fields
	AddinPaneTitle                                   string `json:"addin_pane_title"`
	AddinPaneDescription                             string `json:"addin_pane_description"`
	AddinPaneButtonTitle                             string `json:"addin_pane_button_title"`
	AddinPaneSuccessHeading                          string `json:"addin_pane_success_heading"`
	AddinPaneSuccessMessage                          string `json:"addin_pane_success_message"`
	AddinPaneAlreadyVideoMeetingHeading              string `json:"addin_pane_already_video_meeting_heading"`
	AddinPaneAlreadyVideoMeetingMessage              string `json:"addin_pane_already_video_meeting_message"`
	AddinPaneGeneralErrorHeading                     string `json:"addin_pane_general_error_heading"`
	AddinPaneGeneralErrorMessage                     string `json:"addin_pane_general_error_message"`
	AddinPaneManagementNodeDownHeading               string `json:"addin_pane_management_node_down_heading"`
	AddinPaneManagementNodeDownMessage               string `json:"addin_pane_management_node_down_message"`
	AddinPanePersonalVmrAddButton                    string `json:"addin_pane_personal_vmr_add_button"`
	AddinPanePersonalVmrSignInButton                 string `json:"addin_pane_personal_vmr_sign_in_button"`
	AddinPanePersonalVmrSelectMessage                string `json:"addin_pane_personal_vmr_select_message"`
	AddinPanePersonalVmrNoneMessage                  string `json:"addin_pane_personal_vmr_none_message"`
	AddinPanePersonalVmrErrorGettingMessage          string `json:"addin_pane_personal_vmr_error_getting_message"`
	AddinPanePersonalVmrErrorSigningInMessage        string `json:"addin_pane_personal_vmr_error_signing_in_message"`
	AddinPanePersonalVmrErrorInsertingMeetingMessage string `json:"addin_pane_personal_vmr_error_inserting_meeting_message"`
	// Personal VMR OAuth fields
	PersonalVmrOauthClientID                   *string `json:"personal_vmr_oauth_client_id,omitempty"`
	PersonalVmrOauthClientSecret               string  `json:"personal_vmr_oauth_client_secret,omitempty"`
	PersonalVmrOauthAuthEndpoint               string  `json:"personal_vmr_oauth_auth_endpoint,omitempty"`
	PersonalVmrOauthTokenEndpoint              string  `json:"personal_vmr_oauth_token_endpoint,omitempty"`
	PersonalVmrAdfsRelyingPartyTrustIdentifier string  `json:"personal_vmr_adfs_relying_party_trust_identifier,omitempty"`
	// Template fields
	MeetingInstructionsTemplate         string `json:"meeting_instructions_template,omitempty"`
	PersonalVmrInstructionsTemplate     string `json:"personal_vmr_instructions_template,omitempty"`
	PersonalVmrLocationTemplate         string `json:"personal_vmr_location_template,omitempty"`
	PersonalVmrNameTemplate             string `json:"personal_vmr_name_template,omitempty"`
	PersonalVmrDescriptionTemplate      string `json:"personal_vmr_description_template,omitempty"`
	PlaceholderInstructionsTemplate     string `json:"placeholder_instructions_template,omitempty"`
	ConferenceNameTemplate              string `json:"conference_name_template,omitempty"`
	ConferenceDescriptionTemplate       string `json:"conference_description_template,omitempty"`
	ConferenceSubjectTemplate           string `json:"conference_subject_template,omitempty"`
	ScheduledAliasDescriptionTemplate   string `json:"scheduled_alias_description_template,omitempty"`
	AcceptNewSingleMeetingTemplate      string `json:"accept_new_single_meeting_template,omitempty"`
	AcceptNewRecurringSeriesTemplate    string `json:"accept_new_recurring_series_template,omitempty"`
	AcceptEditedSingleMeetingTemplate   string `json:"accept_edited_single_meeting_template,omitempty"`
	AcceptEditedRecurringSeriesTemplate string `json:"accept_edited_recurring_series_template,omitempty"`
	AcceptEditedOccurrenceTemplate      string `json:"accept_edited_occurrence_template,omitempty"`
	RejectGeneralErrorTemplate          string `json:"reject_general_error_template,omitempty"`
	RejectAliasConflictTemplate         string `json:"reject_alias_conflict_template,omitempty"`
	RejectAliasDeletedTemplate          string `json:"reject_alias_deleted_template,omitempty"`
	RejectInvalidAliasIDTemplate        string `json:"reject_invalid_alias_id_template,omitempty"`
	RejectSingleMeetingPast             string `json:"reject_single_meeting_past,omitempty"`
	RejectRecurringSeriesPastTemplate   string `json:"reject_recurring_series_past_template,omitempty"`
	// JavaScript and CSS URLs
	OfficeJsURL                  string `json:"office_js_url"`
	MicrosoftFabricURL           string `json:"microsoft_fabric_url"`
	MicrosoftFabricComponentsURL string `json:"microsoft_fabric_components_url"`
	AdditionalAddInScriptSources string `json:"additional_add_in_script_sources,omitempty"`
	// Related resources
	Domains                   *string `json:"domains,omitempty"`
	HostIdentityProviderGroup *string `json:"host_identity_provider_group,omitempty"`
	IvrTheme                  *string `json:"ivr_theme,omitempty"`
	NonIdpParticipants        string  `json:"non_idp_participants,omitempty"`
}

// MsExchangeConnectorUpdateRequest represents a request to update a Microsoft Exchange connector
type MsExchangeConnectorUpdateRequest struct {
	Name                       string  `json:"name,omitempty"`
	Description                string  `json:"description,omitempty"`
	RoomMailboxEmailAddress    *string `json:"room_mailbox_email_address,omitempty"`
	RoomMailboxName            string  `json:"room_mailbox_name,omitempty"`
	URL                        string  `json:"url,omitempty"`
	Username                   string  `json:"username,omitempty"`
	Password                   string  `json:"password,omitempty"`
	AuthenticationMethod       string  `json:"authentication_method,omitempty"`
	AuthProvider               string  `json:"auth_provider,omitempty"`
	UUID                       string  `json:"uuid,omitempty"`
	ScheduledAliasPrefix       *string `json:"scheduled_alias_prefix,omitempty"`
	ScheduledAliasDomain       string  `json:"scheduled_alias_domain,omitempty"`
	ScheduledAliasSuffixLength *int    `json:"scheduled_alias_suffix_length,omitempty"`
	MeetingBufferBefore        *int    `json:"meeting_buffer_before,omitempty"`
	MeetingBufferAfter         *int    `json:"meeting_buffer_after,omitempty"`
	EnableDynamicVmrs          *bool   `json:"enable_dynamic_vmrs,omitempty"`
	EnablePersonalVmrs         *bool   `json:"enable_personal_vmrs,omitempty"`
	AllowNewUsers              *bool   `json:"allow_new_users,omitempty"`
	DisableProxy               *bool   `json:"disable_proxy,omitempty"`
	UseCustomAddInSources      *bool   `json:"use_custom_add_in_sources,omitempty"`
	EnableAddinDebugLogs       *bool   `json:"enable_addin_debug_logs,omitempty"`
	// OAuth fields
	OauthClientID      *string `json:"oauth_client_id,omitempty"`
	OauthClientSecret  string  `json:"oauth_client_secret,omitempty"`
	OauthAuthEndpoint  string  `json:"oauth_auth_endpoint,omitempty"`
	OauthTokenEndpoint string  `json:"oauth_token_endpoint,omitempty"`
	OauthRedirectURI   string  `json:"oauth_redirect_uri,omitempty"`
	OauthRefreshToken  string  `json:"oauth_refresh_token,omitempty"`
	// Kerberos fields
	KerberosRealm                  string `json:"kerberos_realm,omitempty"`
	KerberosKdc                    string `json:"kerberos_kdc,omitempty"`
	KerberosKdcHttpsProxy          string `json:"kerberos_kdc_https_proxy,omitempty"`
	KerberosExchangeSpn            string `json:"kerberos_exchange_spn,omitempty"`
	KerberosEnableTls              *bool  `json:"kerberos_enable_tls,omitempty"`
	KerberosAuthEveryRequest       *bool  `json:"kerberos_auth_every_request,omitempty"`
	KerberosVerifyTlsUsingCustomCa *bool  `json:"kerberos_verify_tls_using_custom_ca,omitempty"`
	// Add-in fields
	AddinServerDomain           string  `json:"addin_server_domain,omitempty"`
	AddinDisplayName            string  `json:"addin_display_name,omitempty"`
	AddinDescription            string  `json:"addin_description,omitempty"`
	AddinProviderName           string  `json:"addin_provider_name,omitempty"`
	AddinButtonLabel            string  `json:"addin_button_label,omitempty"`
	AddinGroupLabel             string  `json:"addin_group_label,omitempty"`
	AddinSupertipTitle          string  `json:"addin_supertip_title,omitempty"`
	AddinSupertipDescription    string  `json:"addin_supertip_description,omitempty"`
	AddinApplicationID          *string `json:"addin_application_id,omitempty"`
	AddinAuthorityURL           string  `json:"addin_authority_url,omitempty"`
	AddinOidcMetadataURL        string  `json:"addin_oidc_metadata_url,omitempty"`
	AddinAuthenticationMethod   string  `json:"addin_authentication_method,omitempty"`
	AddinNaaWebApiApplicationID *string `json:"addin_naa_web_api_application_id,omitempty"`
	// Add-in pane fields
	AddinPaneTitle                                   string `json:"addin_pane_title,omitempty"`
	AddinPaneDescription                             string `json:"addin_pane_description,omitempty"`
	AddinPaneButtonTitle                             string `json:"addin_pane_button_title,omitempty"`
	AddinPaneSuccessHeading                          string `json:"addin_pane_success_heading,omitempty"`
	AddinPaneSuccessMessage                          string `json:"addin_pane_success_message,omitempty"`
	AddinPaneAlreadyVideoMeetingHeading              string `json:"addin_pane_already_video_meeting_heading,omitempty"`
	AddinPaneAlreadyVideoMeetingMessage              string `json:"addin_pane_already_video_meeting_message,omitempty"`
	AddinPaneGeneralErrorHeading                     string `json:"addin_pane_general_error_heading,omitempty"`
	AddinPaneGeneralErrorMessage                     string `json:"addin_pane_general_error_message,omitempty"`
	AddinPaneManagementNodeDownHeading               string `json:"addin_pane_management_node_down_heading,omitempty"`
	AddinPaneManagementNodeDownMessage               string `json:"addin_pane_management_node_down_message,omitempty"`
	AddinPanePersonalVmrAddButton                    string `json:"addin_pane_personal_vmr_add_button,omitempty"`
	AddinPanePersonalVmrSignInButton                 string `json:"addin_pane_personal_vmr_sign_in_button,omitempty"`
	AddinPanePersonalVmrSelectMessage                string `json:"addin_pane_personal_vmr_select_message,omitempty"`
	AddinPanePersonalVmrNoneMessage                  string `json:"addin_pane_personal_vmr_none_message,omitempty"`
	AddinPanePersonalVmrErrorGettingMessage          string `json:"addin_pane_personal_vmr_error_getting_message,omitempty"`
	AddinPanePersonalVmrErrorSigningInMessage        string `json:"addin_pane_personal_vmr_error_signing_in_message,omitempty"`
	AddinPanePersonalVmrErrorInsertingMeetingMessage string `json:"addin_pane_personal_vmr_error_inserting_meeting_message,omitempty"`
	// Personal VMR OAuth fields
	PersonalVmrOauthClientID                   *string `json:"personal_vmr_oauth_client_id,omitempty"`
	PersonalVmrOauthClientSecret               string  `json:"personal_vmr_oauth_client_secret,omitempty"`
	PersonalVmrOauthAuthEndpoint               string  `json:"personal_vmr_oauth_auth_endpoint,omitempty"`
	PersonalVmrOauthTokenEndpoint              string  `json:"personal_vmr_oauth_token_endpoint,omitempty"`
	PersonalVmrAdfsRelyingPartyTrustIdentifier string  `json:"personal_vmr_adfs_relying_party_trust_identifier,omitempty"`
	// Template fields
	MeetingInstructionsTemplate         string `json:"meeting_instructions_template,omitempty"`
	PersonalVmrInstructionsTemplate     string `json:"personal_vmr_instructions_template,omitempty"`
	PersonalVmrLocationTemplate         string `json:"personal_vmr_location_template,omitempty"`
	PersonalVmrNameTemplate             string `json:"personal_vmr_name_template,omitempty"`
	PersonalVmrDescriptionTemplate      string `json:"personal_vmr_description_template,omitempty"`
	PlaceholderInstructionsTemplate     string `json:"placeholder_instructions_template,omitempty"`
	ConferenceNameTemplate              string `json:"conference_name_template,omitempty"`
	ConferenceDescriptionTemplate       string `json:"conference_description_template,omitempty"`
	ConferenceSubjectTemplate           string `json:"conference_subject_template,omitempty"`
	ScheduledAliasDescriptionTemplate   string `json:"scheduled_alias_description_template,omitempty"`
	AcceptNewSingleMeetingTemplate      string `json:"accept_new_single_meeting_template,omitempty"`
	AcceptNewRecurringSeriesTemplate    string `json:"accept_new_recurring_series_template,omitempty"`
	AcceptEditedSingleMeetingTemplate   string `json:"accept_edited_single_meeting_template,omitempty"`
	AcceptEditedRecurringSeriesTemplate string `json:"accept_edited_recurring_series_template,omitempty"`
	AcceptEditedOccurrenceTemplate      string `json:"accept_edited_occurrence_template,omitempty"`
	RejectGeneralErrorTemplate          string `json:"reject_general_error_template,omitempty"`
	RejectAliasConflictTemplate         string `json:"reject_alias_conflict_template,omitempty"`
	RejectAliasDeletedTemplate          string `json:"reject_alias_deleted_template,omitempty"`
	RejectInvalidAliasIDTemplate        string `json:"reject_invalid_alias_id_template,omitempty"`
	RejectSingleMeetingPast             string `json:"reject_single_meeting_past,omitempty"`
	RejectRecurringSeriesPastTemplate   string `json:"reject_recurring_series_past_template,omitempty"`
	// JavaScript and CSS URLs
	OfficeJsURL                  string `json:"office_js_url,omitempty"`
	MicrosoftFabricURL           string `json:"microsoft_fabric_url,omitempty"`
	MicrosoftFabricComponentsURL string `json:"microsoft_fabric_components_url,omitempty"`
	AdditionalAddInScriptSources string `json:"additional_add_in_script_sources,omitempty"`
	// Related resources
	Domains                   *string `json:"domains,omitempty"`
	HostIdentityProviderGroup *string `json:"host_identity_provider_group,omitempty"`
	IvrTheme                  *string `json:"ivr_theme,omitempty"`
	NonIdpParticipants        string  `json:"non_idp_participants,omitempty"`
}

// MsExchangeConnectorListResponse represents the response from listing Microsoft Exchange connectors
type MsExchangeConnectorListResponse struct {
	Meta struct {
		Limit      int    `json:"limit"`
		Next       string `json:"next"`
		Offset     int    `json:"offset"`
		Previous   string `json:"previous"`
		TotalCount int    `json:"total_count"`
	} `json:"meta"`
	Objects []MsExchangeConnector `json:"objects"`
}
